version: 0.2

phases:
  pre_build:
    commands:
      - echo Setting up code artifact envs...
      - CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain xitricon --domain-owner 411194283529 --query authorizationToken --output text`
      - AWS_USERNAME=Amila
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 411194283529.dkr.ecr.us-east-1.amazonaws.com
#      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - COMMIT_HASH=0.1.0
      - docker run -d -p 27017:27017 public.ecr.aws/docker/library/mongo:4.4.15
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Application
      - mvn clean install -DskipTests -s settings.xml
      - echo Executing Unit tests and Sonar
      - mvn clean install -s settings.xml jacoco:prepare-agent install jacoco:report sonar:sonar  -Dsonar.host.url=http://sonarcube.navulia.cloud/ -Dsonar.login=${SONAR_KEY} -Dsonar.projectKey=nv-questionnaire-service -Dsonar.projectName='nv-questionnaire-service'
      - echo Building Docker Image
      - docker build -t questionnaire-service:${COMMIT_HASH} . 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging and Pushing the Docker image to ECR
      - docker tag questionnaire-service:${COMMIT_HASH} 411194283529.dkr.ecr.us-east-1.amazonaws.com/questionnaire-service:${COMMIT_HASH}
      - docker push 411194283529.dkr.ecr.us-east-1.amazonaws.com/questionnaire-service:${COMMIT_HASH}
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.m2/**/*'