apiVersion: v1
kind: Service
metadata:
  name: questionnaire-nodeport-service
  labels:
   app: questionnaire-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  selector:
    app: questionnaire-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
...
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: questionnaire-service
  name: questionnaire-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-service
  strategy: {}
  template:
    metadata:
      labels:
        app: questionnaire-service
    spec:
      containers:
        - image: 411194283529.dkr.ecr.us-east-1.amazonaws.com/questionnaire-service:1.0.0
          name: questionnaire-service
          ports:
            - containerPort: 8080
          resources: {}
          imagePullPolicy: Always
          env:
           - name: MONGO_HOST
             value: nv-nonprod-mongodb.navulia.cloud
           - name: MONGO_USERNAME
             value: serviceuser
           - name: MONGO_PASSWORD
             value: serviceUI673BGH
           - name: SPRING_PROFILES_ACTIVE
             value: dev